Repository liyunfan1223/mod-playerbots, pull requests merged in 2025-08, with the labels that each got.

#1521 Playerbots/LFG: fix false “not eligible” & dungeon 0/type 0, add clear diagnostics
  src/PlayerbotMgr.cpp
  src/Playerbots.cpp
Labels: Waiting to be Tested

#1486 Tame Chat Action / Pet Chat Action (stances/commands)
  conf/playerbots.conf.dist
  src/PlayerbotAIConfig.cpp
  src/PlayerbotAIConfig.h
  src/strategy/actions/ActionContext.h
  src/strategy/actions/ChatActionContext.h
  src/strategy/actions/FollowActions.cpp
  src/strategy/actions/GenericActions.cpp
  src/strategy/actions/GenericActions.h
  src/strategy/actions/PetAction.cpp
  src/strategy/actions/PetAction.h
  src/strategy/actions/TameAction.cpp
  src/strategy/actions/TameAction.h
  src/strategy/actions/WorldPacketActionContext.h
  src/strategy/deathknight/GenericDKNonCombatStrategy.cpp
  src/strategy/deathknight/GenericDKStrategy.cpp
  src/strategy/druid/GenericDruidNonCombatStrategy.cpp
  src/strategy/druid/GenericDruidStrategy.cpp
  src/strategy/generic/ChatCommandHandlerStrategy.cpp
  src/strategy/generic/CombatStrategy.cpp
  src/strategy/hunter/GenericHunterNonCombatStrategy.cpp
  src/strategy/mage/FrostMageStrategy.cpp
  src/strategy/priest/GenericPriestStrategy.cpp
  src/strategy/priest/PriestNonCombatStrategy.cpp
  src/strategy/shaman/GenericShamanStrategy.cpp
  src/strategy/shaman/ShamanNonCombatStrategy.cpp
  src/strategy/triggers/ChatTriggerContext.h
  src/strategy/triggers/GenericTriggers.cpp
  src/strategy/triggers/GenericTriggers.h
  src/strategy/triggers/TriggerContext.h
  src/strategy/warlock/GenericWarlockNonCombatStrategy.cpp
Labels: Waiting to be Tested, Requires WIKI update, Multibot requires update

#1510 increase flexibility of multiple bot chatfiltering
  src/ChatFilter.cpp
Labels: Multibot requires update
